import type { Metadata } from 'next';
import { Space_Grotesk } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { Container } from '@/components/shared/Container';

const grotesk = Space_Grotesk({
    weight: ['400', '500'],
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={grotesk.className}>
                <Container>
                    <header className={cn('test', 'tees3')}>Header</header>
                    {children}
                    <footer>Footer</footer>
                </Container>
            </body>
        </html>
    );
}
